# Generated by Django 3.2 on 2023-02-24 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0003_alter_todo_done_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='executors',
            field=models.ManyToManyField(blank=True, null=True, related_name='executors', to=settings.AUTH_USER_MODEL),
        ),
    ]
